<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTeamTableMappingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('team_table_mappings', function (Blueprint $table) {
            $table->increments('id');
            $table->string('table_name', 60)->nullable();
            $table->string('table_id', 60)->nullable();
            $table->string('team_id', 60)->nullable();
            $table->text('table_structure')->nullable();
            $table->string('auth', 20)->nullable()->default('');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('team_table_mappings');
    }
}
